name: Tests
on:
  push:
  pull_request:

jobs:
  test:
    name: ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
      fail-fast: false

    steps:
      - name: Checkout redmine_plugin_kit
        uses: actions/checkout@v5
        with:
          path: redmine_plugin_kit

      - name: Update package archives
        run: sudo apt-get update --yes --quiet

      - name: Install package dependencies
        run: >
          sudo apt-get install --yes --quiet
          build-essential
          cmake
          libicu-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Ruby dependencies
        working-directory: redmine_plugin_kit
        run: |
          bundle install --jobs=4 --retry=3

      - name: Run tests
        env:
          RAILS_ENV: test
        working-directory: redmine_plugin_kit
        run: rake test RUBYOPT="-W0"
